### ISSUE TITLE
300112017

### ISSUE THREAD

**Issue by setrar** [CollegeBoreal/INF1089-200-20H-02#4]
- [ ] Que fait le programme?
- [ ] La page README.md ne donne pas d'explication.

**Comment by ordenrosae** [comment]
j'ajoute une documentation

**Comment by ordenrosae** [comment]
dire ce que le projet fait

**Comment by setrar** [comment]
[P.Projets](https://github.com/CollegeBoreal/INF1089-200-20H-02/tree/master/P.Projets)

Oui, comme le precise l'énoncé

**Comment by ordenrosae** [comment]
il faut voir pour moi si le code marche merci

**Comment by setrar** [comment]
@ordenrosae, J'ai éxécuté le code et il tourne mais je ne sais pas ce qu'il fait. Il faut que tu m'expliques dans le README.md

```
$ python b300112017.py
```

**Comment by ordenrosae** [comment]
le code donne pas de resultat

**Comment by ordenrosae** [comment]
je viens de faire le readme

**Comment by setrar** [comment]
> je viens de faire le readme

- [ x] README.md 

- [ x] Programme Python 

Je vais vérifier le programme et te retourner

**Comment by ordenrosae** [comment]
ok thanks

**Comment by ordenrosae** [comment]
je voudrais juste savoir pour voir si c'est bien
